name: Deploy on Commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SSH connection check
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            echo "Successfully connected!"
            ls -al /home/azureuser/soap-auth-demo
      - name: Deploy file via SCP
        uses: appleboy/scp-action@v0.1.7 # <--- Use the dedicated SCP action
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          source: 'app.py' # <--- This input now works correctly
          target: '/home/azureuser/soap-auth-demo/app.py' # <--- This is the remote path